apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.name }}-ns
spec:
  selector:
    matchLabels:
{{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ $value | quote }}
{{- end }}
  template:
    metadata:
      name: {{ .Values.metadata.name }}
      labels:
{{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
{{- end }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.container.resources.requests.memory }}
              cpu: {{ .Values.container.resources.requests.cpu }}
            limits:
              memory: {{ .Values.container.resources.limits.memory }}
              cpu: {{ .Values.container.resources.limits.cpu }}