apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}-svc
  namespace: {{ .Values.metadata.name}}-ns
  selector:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}