metadata:
  name: webapp
labels:
  app: webapp
container:
  name: webapp
  image: kodekloud/webapp-color
  #tag: v1
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      memory: "256Mi"
      cpu: "500m"
service: 
  port: 8080
  targetPort: 80